allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  lefthook: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@eslint/plugin-kit@0.7.2'
  - dependency-cruiser@17.4.3
  - eslint@10.4.1
  - lefthook-darwin-arm64@2.1.9
  - lefthook-darwin-x64@2.1.9
  - lefthook-freebsd-arm64@2.1.9
  - lefthook-freebsd-x64@2.1.9
  - lefthook-linux-arm64@2.1.9
  - lefthook-linux-x64@2.1.9
  - lefthook-openbsd-arm64@2.1.9
  - lefthook-openbsd-x64@2.1.9
  - lefthook-windows-arm64@2.1.9
  - lefthook-windows-x64@2.1.9
  - lefthook@2.1.9
  - terra-draw@1.31.0
onlyBuiltDependencies:
  - lefthook
  - oniguruma
