name: 'New Feature Request'
description: 'Suggest an idea for this project'
title: '[FEATURE] '
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request! Before filling this feature request, please make sure that:
        - You have the latest version of the project.
        - You have searched the [issues](https://github.com/watergis/maplibre-gl-terradraw/issues) for similar feature requests.

  - type: dropdown
    id: items
    attributes:
      label: Select an item which related to this issue
      multiple: true
      options:
        - maplibre-gl-terradraw
        - Documentation
    validations:
      required: true

  - type: textarea
    id: feature-description
    attributes:
      label: 'Feature Description'
      description: 'A clear and concise description of what the feature is.'
    validations:
      required: true
